backend:
  build: .
  command: bash start.sh
  volumes:
    - ./:/app:rw
  ports:
    - "3000:3000"
  links:
    - postgres
    - redis

postgres:
  image: macadmins/postgres
  ports:
    - '5432:5432'
  environment:
    - DB_NAME=postgres
    - DB_PASS=1234
  volumes:
    - ./_db:/var/lib/postgresql/data

redis:
  image: redis
  ports:
    - "6379:6379"