default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 1234
  host: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: block_chain_certificate_development
test:
  <<: *default
  database: block_chain_certificate_test

production:
  adapter: postgresql
  url: <%= ENV["DATABASE_URL"] %>
